### ISSUE TITLE
除了电脑配置，像摄像头精度有要求吗？

### ISSUE THREAD

**Issue by Lihongjian520** [CoderEugene/DL-Gesture-Recognition#7]
我想跑个6分类的话，可以用PC端来实现吗？？？？

**Comment by govzhz** [comment]
普通的网络摄像头就可以了

**Comment by Lihongjian520** [comment]
还有我应该怎么改才好，你好像是用的是服务器，我想用用电脑自带的

**Comment by govzhz** [comment]
摄像头本身就是在客户端的，如果没有外接摄像头，默认应该就会调用电脑自带的

**Comment by govzhz** [comment]
采用C/S只是为了减少对客户端GPU要求，如果电脑性能足够也完全把客户端和服务器端都部署在同一台电脑上

**Comment by Lihongjian520** [comment]
我把手势识别服务器地址改为0，有界面出来，但是还是识别不了，下面是报错
Exception in thread Thread-4:
Traceback (most recent call last):
  File "D:\python3\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "D:\python3\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "E:\vpn\DL-Gesture-Recognition-master\ops\gesture_rec.py", line 130, in _predict
    res = json.loads(requests.get(self._server_address + "/category_network").text)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
能帮我解决下吗？谢谢
